### ISSUE TITLE
Feature request: Allow for targets to be defined from url parameters.

### ISSUE THREAD

**Issue by jsenecal** [exaring/openconfig-streaming-telemetry-exporter#16]
Hi,

It would be nice if targets could be defined from prometheus instead of the config.yml file in a way similar to [snmp-exporter](https://github.com/prometheus/snmp_exporter#prometheus-configuration).

targets could support a `template` boolean along with `name` and `lifetime_m` fields like such:
```yaml
targets:
- name: jticore
  template: true
  lifetime_m: 1
  # Port of the openconfig target
  port: 50051
  # GRPC keepalive in seconds
  keepalive_s: 1
  # GRPC timeout in seconds
  timeout_s: 3
  # Openconfig paths to subscribe to
  paths:
    # Network interfaces metrics path
  - path: /interfaces/
    # Suppress updates for not changed metrics
    suppress_unchanged: false
    # Maximum time between updates
    max_silent_interval_ms: 20000
    # Sample frequency
    sample_frequency_ms: 2000
```
`lifetime_m` defines how long to keep the subscription alive when no query has been received.

prometheus could then be configured like such:
```yaml
scrape_configs:
  - job_name: 'streaming_telemetry'
    static_configs:
      - targets:
        - 192.168.1.2  # target device.
        - switch.local # target device.
    metrics_path: /metrics
    params:
      target_template: [jticore]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9513 # The openconfig streaming telemetry exporter's real hostname:port.
```

Implementing this would allow for target discovery using built in SD configurations of prometheus.
