### ISSUE TITLE
prometheus/common migrated to main branch

### ISSUE THREAD

**Issue by mweinelt** [exaring/openconfig-streaming-telemetry-exporter#9]
The prometheus/common library migrated to the `main` branch, hence the following reference broke.

```toml
[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"
```
